import type { InsightPage } from "@/lib/cms/types";

export const articleBlueprints = [
  { translationKey: "article-smart-factory-roi", slug: "why-speed-is-the-missing-link-in-automotive-smart-factory-roi", title: "Why speed is the missing link in automotive smart factory ROI", summary: "Speed to operational learning is what turns factory pilots into ROI, not the number of sensors installed.", authorId: "author-bryan-powrozek", publishedAt: "2026-05-18", readTime: "5 min read", topics: ["Manufacturing", "Technology consulting"], relatedServiceIds: ["service-platform"], relatedIndustryIds: [], cardImage: { src: "https://images.unsplash.com/photo-1565008447742-97f6f38c985c?auto=format&fit=crop&w=1200&q=80", alt: "Engineer reviewing a smart factory floor" }, body: ["Manufacturers do not struggle because they lack use cases. They struggle because decision cycles are too slow to convert pilot signals into real production changes.", "The strongest smart-factory programs set up operating rhythms around experiment review, local plant ownership, and ROI checkpoints that can be acted on inside a quarter."] },
  { translationKey: "article-bank-fdicia", slug: "cfos-if-your-bank-is-approaching-1-billion-in-assets-you-cant-keep-putting-off-fdicia", title: "CFOs: If your bank is approaching $1 billion in assets, you can't keep putting off FDICIA", summary: "Banks approaching the threshold need governance, controls, and reporting discipline before the deadline pressure peaks.", authorId: "author-nick-ansley", publishedAt: "2026-05-15", readTime: "6 min read", topics: ["Financial services", "Risk advisory"], relatedServiceIds: ["service-risk"], relatedIndustryIds: [], cardImage: { src: "https://images.unsplash.com/photo-1556740749-887f6717d7e4?auto=format&fit=crop&w=1200&q=80", alt: "Advisors reviewing financial reporting on a laptop" }, body: ["FDICIA readiness is rarely blocked by technical accounting knowledge alone. More often, the issue is fragmented ownership across finance, controls, and internal audit.", "CFOs that start early can phase documentation, testing, and remediation in a way that builds confidence without disrupting growth priorities."] },
  { translationKey: "article-stablecoins-fintech-risk", slug: "stablecoins-represent-a-growing-but-potentially-risky-part-of-the-financial-system-what-do-fintech-leaders-need-to-know", title: "Stablecoins represent a growing but potentially risky part of the financial system. What do fintech leaders need to know?", summary: "Product teams need a clearer view of governance, liquidity exposure, and partner risk before stablecoin use moves from experiment to core flow.", authorId: "author-marybeth-marchione", publishedAt: "2026-05-14", readTime: "5 min read", topics: ["Technology companies", "Risk advisory"], relatedServiceIds: ["service-risk"], relatedIndustryIds: [], cardImage: { src: "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1200&q=80", alt: "Leadership team discussing fintech strategy in a meeting room" }, body: ["Stablecoins have moved from an edge case to a strategic consideration for many fintech operators. That shift raises harder questions about treasury, counterparties, and product controls.", "The right response is not blanket avoidance. It is a more explicit operating model for how emerging payment rails are reviewed, monitored, and escalated."] },
  { translationKey: "article-middle-market-plant-analytics", slug: "why-middle-market-manufacturers-are-redesigning-plant-analytics-now", title: "Why middle-market manufacturers are redesigning plant analytics now", summary: "Plant leaders are moving analytics closer to daily decisions instead of leaving insights trapped in monthly reporting decks.", authorId: "author-bryan-powrozek", publishedAt: "2026-05-12", readTime: "4 min read", topics: ["Manufacturing", "Operations"], relatedServiceIds: ["service-platform"], relatedIndustryIds: [], cardImage: { src: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1200&q=80", alt: "Factory worker reviewing plant analytics on a tablet" }, body: ["The analytics redesign happening in middle-market plants is less about dashboards and more about decision timing. Teams need data framed around shifts, bottlenecks, and maintenance tradeoffs.", "Programs that win start with a small set of operational questions and design the data flow backwards from those moments."] },
  { translationKey: "article-healthcare-ai-governance", slug: "what-healthcare-boards-expect-from-ai-risk-governance-in-2026", title: "What healthcare boards expect from AI risk governance in 2026", summary: "Boards want evidence that AI decisions are governed through clear ownership, clinical context, and auditability.", authorId: "author-nick-ansley", publishedAt: "2026-05-10", readTime: "7 min read", topics: ["Healthcare", "Risk advisory"], relatedServiceIds: ["service-risk"], relatedIndustryIds: ["industry-healthcare"], cardImage: { src: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=1200&q=80", alt: "Healthcare executives discussing governance around AI tools" }, body: ["Healthcare boards are no longer satisfied with broad assurance that AI use is being monitored. They want to know where decisions are made, who can intervene, and what evidence exists when outcomes are challenged.", "That means governance has to be practical enough for operators while still producing decision trails leadership can trust."] },
  { translationKey: "article-commercial-banking-controls", slug: "the-new-operating-model-for-commercial-banking-controls-modernization", title: "The new operating model for commercial banking controls modernization", summary: "Controls programs are shifting from periodic remediation projects to persistent product-and-process ownership.", authorId: "author-nick-ansley", publishedAt: "2026-05-08", readTime: "6 min read", topics: ["Financial services", "Controls"], relatedServiceIds: ["service-risk"], relatedIndustryIds: [], cardImage: { src: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=1200&q=80", alt: "Banking professionals reviewing controls modernization planning" }, body: ["Commercial banking control programs break down when they are staffed like one-time initiatives. The underlying processes evolve too quickly for that model to hold.", "The stronger pattern is product-style ownership with clearer control maps, issue tracking, and reporting tied to the business rhythm."] },
  { translationKey: "article-private-equity-data-room", slug: "how-private-equity-portfolio-teams-are-using-data-rooms-after-close", title: "How private equity portfolio teams are using data rooms after close", summary: "The best portfolio teams are turning diligence structures into operating assets for the first 180 days after close.", authorId: "author-alicia-roberts", publishedAt: "2026-05-05", readTime: "5 min read", topics: ["Private equity", "Data strategy"], relatedServiceIds: ["service-platform"], relatedIndustryIds: [], cardImage: { src: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1200&q=80", alt: "Private equity team in a conference room reviewing portfolio materials" }, body: ["Too many data rooms become archival storage the moment a transaction closes. Leading portfolio teams are reusing that structure to accelerate value-creation planning.", "The benefit is less duplication and a cleaner handoff into operating dashboards, workplans, and leadership reviews."] },
  { translationKey: "article-energy-self-service-reset", slug: "what-energy-suppliers-gain-from-a-digital-self-service-reset", title: "What energy suppliers gain from a digital self-service reset", summary: "Self-service redesign pays off when customer flows reduce friction for both end users and service teams.", authorId: "author-devon-cho", publishedAt: "2026-05-03", readTime: "4 min read", topics: ["Energy", "Customer experience"], relatedServiceIds: ["service-platform"], relatedIndustryIds: [], cardImage: { src: "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?auto=format&fit=crop&w=1200&q=80", alt: "Energy operations team discussing digital customer service workflows" }, body: ["Energy suppliers are under pressure to make digital service simpler while keeping exception handling safe and compliant. That usually requires resetting the workflow, not just refreshing the interface.", "The most credible programs map customer effort, internal handoffs, and escalation logic as one connected design problem."] },
  { translationKey: "article-wealth-compliance-workflows", slug: "a-practical-roadmap-for-wealth-firms-modernizing-compliance-workflows", title: "A practical roadmap for wealth firms modernizing compliance workflows", summary: "Workflow modernization works when policy intent, user behavior, and evidence capture are redesigned together.", authorId: "author-nick-ansley", publishedAt: "2026-05-01", readTime: "6 min read", topics: ["Wealth management", "Compliance"], relatedServiceIds: ["service-risk"], relatedIndustryIds: [], cardImage: { src: "https://images.unsplash.com/photo-1554224154-26032ffc0d07?auto=format&fit=crop&w=1200&q=80", alt: "Wealth management professionals reviewing compliance workflow steps" }, body: ["Compliance teams often inherit workflows that reflect old organizational boundaries instead of current risk priorities. Modernization should start with where decisions and approvals actually happen now.", "From there, firms can simplify evidence capture, remove duplicate reviews, and improve management visibility without weakening control intent."] },
  { translationKey: "article-insurers-claims-content", slug: "why-insurers-are-rethinking-claims-content-for-digital-first-customers", title: "Why insurers are rethinking claims content for digital-first customers", summary: "Claims journeys are exposing how often content, forms, and service operations are designed separately.", authorId: "author-alicia-roberts", publishedAt: "2026-04-29", readTime: "5 min read", topics: ["Insurance", "Customer experience"], relatedServiceIds: ["service-platform", "service-risk"], relatedIndustryIds: [], cardImage: { src: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=1200&q=80", alt: "Insurance team discussing digital claims communication" }, body: ["Insurers are discovering that digital claims performance is tied closely to the quality of the content customers receive during stressful moments. Content gaps quickly become operational friction.", "Teams that redesign this journey well align plain-language guidance, forms logic, and service escalation around the same customer outcome."] },
  { translationKey: "article-logistics-automation-sequencing", slug: "how-logistics-operators-are-sequencing-automation-without-service-disruption", title: "How logistics operators are sequencing automation without service disruption", summary: "Successful automation programs are staged around service continuity, labor trust, and exception handling capacity.", authorId: "author-devon-cho", publishedAt: "2026-04-27", readTime: "5 min read", topics: ["Logistics", "Automation"], relatedServiceIds: ["service-platform"], relatedIndustryIds: [], cardImage: { src: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1200&q=80", alt: "Warehouse automation in a logistics environment" }, body: ["Logistics leaders know that automation gains can disappear quickly if service levels wobble during rollout. That is why sequencing matters as much as technology selection.", "Programs that work tend to isolate failure modes early, build manual fallback paths, and give site leaders a real voice in the cutover plan."] },
  { translationKey: "article-treasury-transformation-metrics", slug: "three-metrics-that-make-treasury-transformation-programs-believable", title: "Three metrics that make treasury transformation programs believable", summary: "Leadership confidence rises when treasury transformation is translated into measurable resilience, accuracy, and decision speed.", authorId: "author-nick-ansley", publishedAt: "2026-04-24", readTime: "4 min read", topics: ["Treasury", "Transformation"], relatedServiceIds: ["service-risk"], relatedIndustryIds: [], cardImage: { src: "https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?auto=format&fit=crop&w=1200&q=80", alt: "Finance leader reviewing treasury transformation metrics" }, body: ["Treasury programs lose credibility when success is framed in platform language instead of business language. Executives want to know what decisions improve and what risk exposure changes.", "A small metric set tied to liquidity visibility, forecast confidence, and cycle-time reduction usually tells the story better than a long backlog report."] },
  { translationKey: "article-thought-leadership-pipeline", slug: "how-advisory-firms-can-turn-thought-leadership-into-pipeline-signals", title: "How advisory firms can turn thought leadership into pipeline signals", summary: "Editorial programs work better when content journeys, CRM handoffs, and subject-matter ownership are designed together.", authorId: "author-alicia-roberts", publishedAt: "2026-04-22", readTime: "5 min read", topics: ["B2B marketing", "Content strategy"], relatedServiceIds: ["service-platform"], relatedIndustryIds: [], cardImage: { src: "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1200&q=80", alt: "Advisory firm team discussing thought leadership performance" }, body: ["Thought leadership rarely fails because the ideas are weak. It fails because the system around the content does not make the next action obvious.", "Firms that improve conversion tend to define intended audience paths, surface related proof points, and align follow-up processes before publishing volume increases."] },
  { translationKey: "article-b2b-service-microsites", slug: "what-enterprise-buyers-expect-from-b2b-service-microsites-now", title: "What enterprise buyers expect from B2B service microsites now", summary: "Microsites have to feel coherent, credible, and connected to the rest of the buying journey to be worth maintaining.", authorId: "author-alicia-roberts", publishedAt: "2026-04-19", readTime: "4 min read", topics: ["B2B marketing", "Digital experience"], relatedServiceIds: ["service-platform"], relatedIndustryIds: [], cardImage: { src: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=80", alt: "B2B team reviewing a service microsite strategy" }, body: ["Enterprise buyers are less tolerant of disconnected campaign experiences than they were a few years ago. A microsite now has to earn its place in the broader architecture.", "That means stronger navigation, clearer proof, and more intentional connections back to the main service and contact flows."] },
  { translationKey: "article-finance-platform-governance", slug: "a-cfo-guide-to-governance-before-a-finance-platform-migration", title: "A CFO guide to governance before a finance platform migration", summary: "Platform migration decisions land better when governance is clarified before build choices harden into delivery risk.", authorId: "author-nick-ansley", publishedAt: "2026-04-16", readTime: "6 min read", topics: ["Finance", "Governance"], relatedServiceIds: ["service-risk", "service-platform"], relatedIndustryIds: [], cardImage: { src: "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=1200&q=80", alt: "Finance executive planning platform migration governance" }, body: ["Migration programs often concentrate on tool selection too early. Finance leaders create less delivery risk when they define decision rights, escalation paths, and reporting expectations upfront.", "That governance work gives the implementation a steadier shape and reduces the number of late surprises that derail timelines."] },
  { translationKey: "article-healthcare-access-orchestration", slug: "what-health-systems-learn-when-patient-access-orchestration-finally-gets-measured", title: "What health systems learn when patient access orchestration finally gets measured", summary: "Patient access redesign becomes more credible when teams can see wait-time friction, content confusion, and handoff loss in one picture.", authorId: "author-devon-cho", publishedAt: "2026-04-14", readTime: "5 min read", topics: ["Healthcare", "Operations"], relatedServiceIds: ["service-platform", "service-risk"], relatedIndustryIds: ["industry-healthcare"], cardImage: { src: "https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=1200&q=80", alt: "Healthcare operations team planning patient access improvements" }, body: ["Patient access problems usually span staffing, process design, digital content, and system handoffs. Measuring only one of those layers hides the actual bottlenecks.", "Health systems that orchestrate the full journey can make smarter staffing choices and simplify how patients move from intent to scheduled care."] },
  { translationKey: "article-industrial-safety-dashboards", slug: "why-industrial-safety-dashboards-fail-without-line-supervisor-ownership", title: "Why industrial safety dashboards fail without line-supervisor ownership", summary: "Dashboards help only when frontline leaders see them as tools for action rather than compliance artifacts.", authorId: "author-bryan-powrozek", publishedAt: "2026-04-12", readTime: "4 min read", topics: ["Manufacturing", "Safety"], relatedServiceIds: ["service-platform"], relatedIndustryIds: [], cardImage: { src: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=1200&q=80", alt: "Industrial supervisor reviewing safety and operations data" }, body: ["Safety dashboards fail when they are designed for executive reporting but expected to change frontline behavior. The daily owner has to see a clear decision inside the data.", "Line supervisors adopt tools faster when the metrics connect directly to shift planning, escalation, and near-term risk reduction."] },
] as const;

export function createArticleInsightPage(article: (typeof articleBlueprints)[number]): InsightPage {
  return {
    id: `${article.translationKey}-en`,
    translationKey: article.translationKey,
    type: "insight",
    locale: "en",
    status: "published",
    slug: ["article", article.slug],
    title: article.title,
    eyebrow: "Article",
    summary: article.summary,
    seo: {
      title: `${article.title} | Summit Advisory Group`,
      description: article.summary,
    },
    authorId: article.authorId,
    publishedAt: article.publishedAt,
    readTime: article.readTime,
    topics: [...article.topics],
    relatedServiceIds: [...article.relatedServiceIds],
    relatedIndustryIds: [...article.relatedIndustryIds],
    cardImage: article.cardImage,
    sections: [
      {
        type: "image",
        src: article.cardImage.src,
        alt: article.cardImage.alt,
        caption: article.summary,
      },
      {
        type: "richText",
        body: [...article.body],
      },
      {
        type: "cta",
        title: "Continue exploring the article library",
        body: "Return to the article hub to browse more stories from the CMS-backed listing.",
        action: {
          label: "View all articles",
          href: "/en/article/all",
        },
        tone: "accent",
      },
    ],
  };
}

export const articleTranslationKeys = articleBlueprints.map((article) => article.translationKey);
export const articleInsightPages = articleBlueprints.map(createArticleInsightPage);
