import type { OptimizelyRichTextField } from "./cms-utils";

export type OptimizelyJsonMetadata = {
  displayName?: string;
  locale?: string;
  status?: string;
  key?: string;
  url?: {
    default?: string;
    hierarchical?: string;
  };
};

export type OptimizelyJsonBlock = {
  __typename?: string;
  title?: string;
  subtitle?: string;
  showDecoration?: boolean;
  decorationColorsPrimary?: string;
  decorationColorsSecondary?: string;
  description?: string;
  story?: string;
  highlights?: string[];
  content?: string;
  fullName?: string;
  position?: string;
  imageSrc?: string;
  name?: string;
  bio?: string;
  logos?: Array<{
    src?: string;
    alt?: string;
  }>;
  services?: Array<{
    title?: string;
    description?: string;
    icon?: string;
    href?: string;
  }>;
  testimonials?: Array<{
    fullName?: string;
    position?: string;
    content?: string;
    avatarSrc?: string;
  }>;
  items?: Array<{
    title?: string;
    description?: string;
    imageUrl?: string;
    link?: string;
  }>;
  imageUrl?: string;
  image?: {
    url?: string;
    alt?: string;
  };
  altText?: string;
  caption?: string;
  videoUrl?: string;
  embedUrl?: string;
  posterImageUrl?: string;
  paragraph_text?: {
    html?: string;
    json?: unknown;
  };
  html?: string;
  json?: unknown;
  body?: string | OptimizelyRichTextField;
  Body?: string | OptimizelyRichTextField;
  richText?: string | OptimizelyRichTextField;
  RichText?: string | OptimizelyRichTextField;
  text?: string | OptimizelyRichTextField;
  Text?: string | OptimizelyRichTextField;
  _metadata?: OptimizelyJsonMetadata;
  introText?: string;
  IntroText?: string;
  emailLabel?: string;
  EmailLabel?: string;
  firstNameLabel?: string;
  FirstNameLabel?: string;
  lastNameLabel?: string;
  LastNameLabel?: string;
  jobTitleLabel?: string;
  JobTitleLabel?: string;
  organizationLabel?: string;
  OrganizationLabel?: string;
  cityLabel?: string;
  CityLabel?: string;
  stateLabel?: string;
  StateLabel?: string;
  phoneLabel?: string;
  PhoneLabel?: string;
  messageLabel?: string;
  MessageLabel?: string;
  emailPlaceholder?: string;
  EmailPlaceholder?: string;
  firstNamePlaceholder?: string;
  FirstNamePlaceholder?: string;
  lastNamePlaceholder?: string;
  LastNamePlaceholder?: string;
  jobTitlePlaceholder?: string;
  JobTitlePlaceholder?: string;
  organizationPlaceholder?: string;
  OrganizationPlaceholder?: string;
  cityPlaceholder?: string;
  CityPlaceholder?: string;
  statePlaceholder?: string;
  StatePlaceholder?: string;
  phonePlaceholder?: string;
  PhonePlaceholder?: string;
  messagePlaceholder?: string;
  MessagePlaceholder?: string;
  submitLabel?: string;
  SubmitLabel?: string;
  successMessage?: string;
  SuccessMessage?: string;
  errorMessage?: string;
  ErrorMessage?: string;
  uploadLabel?: string;
  UploadLabel?: string;
  stateAsDropdown?: string;
  StateAsDropdown?: string;
  officesJson?: string;
  OfficesJson?: string;
  heroImageUrl?: string;
  HeroImageUrl?: string;
  bannerHeading?: string;
  BannerHeading?: string;
  sectionHeading?: string;
  SectionHeading?: string;
  applicationsJson?: string | unknown[];
  ApplicationsJson?: string | unknown[];
  ApplicationsJSON?: string | unknown[];
  logoUrl?: string;
  LogoUrl?: string;
  brandLabel?: string;
  BrandLabel?: string;
  usernameLabel?: string;
  UsernameLabel?: string;
  usernameHelper?: string;
  UsernameHelper?: string;
  passwordLabel?: string;
  PasswordLabel?: string;
  passwordHelper?: string;
  PasswordHelper?: string;
  loginLabel?: string;
  LoginLabel?: string;
  forgotPasswordLabel?: string;
  ForgotPasswordLabel?: string;
  forgotPasswordUrl?: string;
  ForgotPasswordUrl?: string;
  needHelpLabel?: string;
  NeedHelpLabel?: string;
  needHelpUrl?: string;
  NeedHelpUrl?: string;
  oneTimePaymentLabel?: string;
  OneTimePaymentLabel?: string;
  oneTimePaymentUrl?: string;
  OneTimePaymentUrl?: string;
  registerLabel?: string;
  RegisterLabel?: string;
  registerUrl?: string;
  RegisterUrl?: string;
  eventsJson?: string;
  EventsJson?: string;
  variant?: string;
  Variant?: string;
  signInConfigJson?: string;
  SignInConfigJson?: string;
};

